### PR TITLE
dvc_funnel_config

### PR DESCRIPTION
**Pull request by gabrieltorresgamez**
dont merge yet!

### CODE REVIEW

**Comment by ghost** [comment]
# RUN: 2023-04-21 16-56-04

## Hyperparameters

| Path   | Param   | HEAD~1   | workspace   |
|--------|---------|----------|-------------|

## Metrics

| Path   | Metric   | HEAD~1   | workspace   | Change   |
|--------|----------|----------|-------------|----------|

# Plots

TODO

**Comment by gabrieltorresgamez** [comment]
works locally
important: remove server01 from tailscale for it to work
merging to main in hopes that studio recognizes it, since there is no field "endpointurl" in webgui 🤦🏼‍♂️

**Comment by ghost** [comment]
# RUN: 2023-04-21 17-38-17

## Hyperparameters

| Path   | Param   | HEAD~1   | workspace   |
|--------|---------|----------|-------------|

## Metrics

| Path   | Metric   | HEAD~1   | workspace   | Change   |
|--------|----------|----------|-------------|----------|

# Plots

TODO

**Comment by ghost** [comment]
# RUN: 2023-04-21 18-43-32

## Hyperparameters

| Path   | Param   | HEAD~1   | workspace   |
|--------|---------|----------|-------------|

## Metrics

| Path   | Metric   | HEAD~1   | workspace   | Change   |
|--------|----------|----------|-------------|----------|

# Plots

TODO

**Pull request merged**
